project_id = "litmo-local"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["exp://127.0.0.1:8081", "litmo://"]
enable_signup = true

[auth.passkey]
enabled = true

[auth.webauthn]
rp_display_name = "Litmo"
rp_id = "softnessasastrength.com"
rp_origins = ["https://softnessasastrength.com"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[studio]
enabled = true
port = 54323
